Fix location issue
numbersprotocol/lifebox pull request #27
Opened 2021-05-17 06:33 UTC by CS6

High - 使用者第一次紀錄，GPS 權限要要求視窗跳出後，尚未同意權限前，會跳出 Error 訊息 => 會重複詢問直到使用者做出決定
High - 讓使用者可於設定中決定是否 enable GPS 收集，並且不 enable GPS 也可使用 (類似 Capture) 預設不啟用啟用後開始詢問使用者權限
Medium - 設定頁面中 “Other info” 的 About 改為 Contace US (link 到 Numbers Contact US 頁面)

2021-05-17 11:25 UTC, shc261392 requested changes

2021-05-17 11:25 UTC, shc261392 commented on src/assets/i18n/en.json
> +    "about": "Contace US",
```suggestion
    "about": "Contact Us",
```

typo

2021-05-17 11:25 UTC, shc261392 commented on src/app/tabs/settings/settings.page.ts
> +    console.log('event.detail.value', event.detail.value);
Remove the log for debugging

2021-05-17 11:25 UTC, shc261392 commented on src/app/tabs/settings/settings.page.html
> +      <ion-item lines="inset">
`ion-toggle` may be a better choice for this option. I'd suggest use `ion-toggle` instead, but if there isn't enough time to implement it or if it's a UI component requested by PO then it's fine to stick to the current solution for now.

2021-05-17 11:25 UTC, shc261392 commented on src/app/core/services/proof.service.ts
> +    console.log("setLocationInfoCollection",enable);
Remove the debugging log

2021-05-17 11:25 UTC, shc261392 commented on src/app/shared/components/add-record/add-record.component.ts
> +    }
```suggestion
    } else {
      const proof = this.proofService.createProofWithoutLocation();
      this.updateRecordProof(proof);
      this.proofStatus = ProofStatus.COMPLETE);
    }
```

No need to use observable here

2021-05-17 11:25 UTC, shc261392 commented on src/app/core/services/proof.service.ts
> +  createDisableLocationProof(): Observable<Proof> {
The function isn't needed (see the comment in `add-record.component.ts`)

2021-05-17 11:25 UTC, shc261392 commented on src/app/core/services/proof.service.ts
> +    return this.enableGeolocation=enable;
```suggestion
    this.enableGeolocation = enable;
```
No need to return anything (the return value is not used)

2021-05-17 11:25 UTC, shc261392 commented on src/app/core/services/proof.service.ts
> +  enableGeolocation: string = 'disable';
```suggestion
  enableGeolocation = 'disable'; 
```
The initialization already make the variable inferenced as string type, so there's no need for explicit type declaration.

2021-05-17 11:25 UTC, shc261392 commented on src/app/core/services/geolocation.service.ts
> +        .catch<GeolocationPosition>((error) => (error.message as string).includes('0')
The meaning of `(error.message as string).includes('0')` is unclear. It's confusing to people who read the code but don't know what error you are catching, so it's better to rewrite the code in a way that it's easier to understand. Or if it's difficult to be expressive enough in code, write some comments to explain it.

And it doesn't seem necessary to create another function if all you want to do is catching errors. You can catch error using RxJS pipe operator `catchError` chained after `position$`, for example

```
return position$
  .pipe(
    catchError(error => of(undefined)),
```

The above example will  send `undefined` to be handled by the next operator in the pipe if position$ emits error.

2021-05-18 05:22 UTC, CS6 commented on src/app/tabs/settings/settings.page.html
> +      <ion-item lines="inset">
This is the result of discussion with PO

2021-05-19 07:21 UTC, shc261392 approved these changes

2021-05-19 07:21 UTC, merged